---
title: "Preprocess English Data (1)"
output: html_document
---

### Load and inspect data
```{r LoadPackages, message = FALSE}

library(dplyr)
library(lme4)
library(lmerTest)
library(ggplot2)
library(sjPlot)
library(reshape)

#Set working directory and filenames
#setwd("/Users/au571533/Documents/Projects/DeixisOnlineSurvey/Analysis")
filename = 'raw_data_EN.tsv'
data_EN <- read.table(filename, sep = '\t', skip=1, header=TRUE, encoding = "utf-8", skipNul=TRUE)[-c(1),]
data_EN <- data_EN[, -ncol(data_EN)]

# Rename columns and filter out unfinished responses
data_EN <- reshape::rename(data_EN, c(Response.ID = 'ID',
                                      Is.your.native.language.English. = "Native", 
                                      Please.indicate.your.age = 'Age', 
                                      Please.indicate.your.gender = 'Gender',
                                      Which.is.your.native.language. = 'Mother_Tongue', 
                                      Please.tick.the.words.you.do.NOT.understand. = 'Which_Unknown',
                                      Duration..in.seconds. = 'Duration',
                                      Do.you.know.the.meaning.of.all.the.words.you.encountered.in.the.survey. = 'All_Words_Known',
                                      Which.variety.of.English.is.your.native.language....Selected.Choice = 'English_Variety',
                                      Which.variety.of.English.is.your.native.language....Other..please.type.in.....Text = 'English_Variety_Other') 
                                      )

# Reformat some of the columns
data_EN$Duration <- as.numeric(data_EN$Duration)
data_EN <- subset(data_EN, Finished =="True")

# Visualize data
head(data_EN)
rm(filename)
```


### Overall number of data points 
```{r Descriptives, message=FALSE}

paste('Total number of participants', as.character(nrow(data_EN)), sep = ': ')
paste('Total number of native speakers', as.character(nrow(subset(data_EN, Native == 'Yes'))), sep = ': ')
paste('Number participants who knew the meaning of all words', as.character(nrow(subset(data_EN, Which_Unknown == ''))), sep = ': ')
paste('Number female', as.character(nrow(subset(data_EN, Gender == 'Female'))), sep = ': ')

# Age distribution
agg_age <- data_EN %>% group_by(Age) %>% summarize(Number_participants= n())
print('Age distribution')
paste('    18-30', as.character(agg_age$Number_participants[1]), sep = ': ')
paste('    30-40', as.character(agg_age$Number_participants[2]), sep = ': ')
paste('    40-50', as.character(agg_age$Number_participants[3]), sep = ': ')
paste('    50-60', as.character(agg_age$Number_participants[4]), sep = ': ')
paste('    60+  ', as.character(agg_age$Number_participants[5]), sep = ': ')

# Print duration
paste('Average duration (in minutes)', as.character(mean(data_EN$Duration) / 60))

# Clean up
rm(agg_age)

```

### Delete useless columns
```{r DropColsAndReshape, message = FALSE}

# Drop columns
#58, 59, 63
data_EN<-data_EN[ , -c(1:8, 10:17)]

# Reshape
data_EN <- melt(data_EN, id=c('ID','Gender','Age','Native', 'Mother_Tongue', 'English_Variety', 'English_Variety_Other', 'All_Words_Known','Which_Unknown'))

# Remove datapoints with unknown words
data_EN <- subset(data_EN, ID != 'R_2zuqM14h06CGO5u' & ID != 'R_12a8duh06OhgQBJ')
ID_unknown <- unique(subset(data_EN, Which_Unknown != '')$ID)

# Drop one by one
row_drops_1 <- which(data_EN$ID == ID_unknown[1] & data_EN$variable %in% c('thorn' , 'cradle'))
row_drops_2 <- which(data_EN$ID == ID_unknown[2] & data_EN$variable %in% c('robin'))
row_drops_3 <- which(data_EN$ID == ID_unknown[3] & data_EN$variable %in% c('burner' , 'rifle', 'thorn'))
row_drops_4 <- which(data_EN$ID == ID_unknown[4] & data_EN$variable %in% c('burner' , 'quarrel'))
row_drops_5 <- which(data_EN$ID == ID_unknown[5] & data_EN$variable %in% c('flea', 'dagger', 'quarrel'))
row_drops_6 <- which(data_EN$ID == ID_unknown[6] & data_EN$variable %in% c('quarrel'))
row_drops_7 <- which(data_EN$ID == ID_unknown[7] & data_EN$variable %in% c('hyena', 'quarrel'))
row_drops_8 <- which(data_EN$ID == ID_unknown[8] & data_EN$variable %in% c('shrimp', 'quarrel', 'cradle'))
row_drops_9 <- which(data_EN$ID == ID_unknown[9] & data_EN$variable == 'quarrel')
row_drops <- c(row_drops_1, row_drops_2, row_drops_3, row_drops_4, row_drops_5, row_drops_6, row_drops_7, row_drops_8, row_drops_9)
data_EN <- data_EN[-row_drops,]

# Rename columns
data_EN <- reshape::rename(data_EN, c(variable = 'Noun', value ='Demonstrative'))

# Remove useless variables
rm(ID_unknown, row_drops_1, row_drops_2, row_drops_3, row_drops_4, row_drops_5, row_drops_6, row_drops_7, row_drops_8, row_drops_9, row_drops)

```

### Info on experimental words
```{r ExpWords, message=FALSE}

# Add experimental words
Fillers_EN<-c('quarrel', 'deal', 'hurry', 'rest', 'stress', 'rise', 'loss', 'dawn')

Animals_EN <-c('bee', 'flea', 'spider', 'rat', 'bull', 'shark', 'hyena', 'snake', 'camel', 'goose', 'lamb', 'penguin', 'cricket', 'kitten', 'robin', 'shrimp')

Bigger_EN <-c('bull', 'shark', 'hyena', 'snake', 'camel', 'goose', 'lamb', 'penguin', 'bomb','jail', 'rocket', 'rifle', 'bench', 'couch', 'cradle', 'tent')

Harmful_EN <-c('bull','hyena','snake','shark','bee','flea','spider','rat','bomb','jail','rocket','rifle','burner','dagger','needle','thorn')


### Create column "Fillers" and resp. assign values "Fillers" and "Exp_words" based on values in $Noun
data_EN$Fillers <- ifelse(data_EN$Noun %in% Fillers_EN, "Fillers", "Exp_words")
data_EN$Fillers<-factor(data_EN$Fillers)

### Create column "Animal" and resp. assign values "Animate" and "Non_Animate" based on values in $Noun
data_EN$Animate <- ifelse(data_EN$Noun %in% Animals_EN, "Animate", "Non_Animate")
data_EN$Animate<-factor(data_EN$Animate)

### Create column "Size" and resp. assign values "Big" or "Small" based on values in $Noun
data_EN$Size <- ifelse(data_EN$Noun %in% Bigger_EN, "Big", "Small")
data_EN$Size<-factor(data_EN$Size)

### Create column "Harm" and resp. assign values "Harmful" or "Harmless" based on values in $Noun
data_EN$Harm <- ifelse(data_EN$Noun %in% Harmful_EN, "Harmful", "Harmless")
data_EN$Harm<-factor(data_EN$Harm)

# Values of Dems column as values in factor "Demonstratives"
data_EN$Demonstrative <- ifelse(data_EN$Demonstrative == 'this', 'proximal', 'distal')
data_EN$Demonstrative<-factor(data_EN$Demonstrative)

# Remove fillers and delete column
data_EN <- subset(data_EN, Fillers != 'Fillers')
data_EN <- data_EN[, !(colnames(data_EN) %in%  c('Fillers', 'Which_Unknown'))]

# Re-visualize 
head(data_EN)
#write_tsv(data_EN, 'EN_1.txt')

# Remove useless variables
rm(Fillers_EN, Animals_EN, Bigger_EN, Harmful_EN)
```