---
title: "Preprocess Danish Data (2)"
output: html_document
---

# Load and inspect data
```{r LoadPackages, message = FALSE}

library(dplyr)
library(lme4)
library(lmerTest)
library(ggplot2)
library(sjPlot)
library(reshape)

#Set working directory and filenames
#setwd("/Users/au571533/Dropbox/DeixisSurvey")
filename = 'raw_data_DK_2.tsv'
data_DK <- read.table(filename, sep = '\t', skip=1, header=TRUE, encoding = "utf-8", skipNul=TRUE)[-c(1),]

# Rename columns and filter out unfinished responses
data_DK <- reshape::rename(data_DK, c(Response.ID = 'ID',
                                      Er.dit.modersm.l.dansk. = "Native", 
                                      Hvad.er.din.alder. = 'Age', 
                                      Hvad.er.dit.k.n. = 'Gender',
                                      Hvad.er.dit.modersm.l. = 'Mother_Tongue', 
                                      Klik.p..de.ord..du.IKKE.kender.betydningen.af. = 'Which_Unknown',
                                      Duration..in.seconds. = 'Duration',
                                      Kendte.du.betydningen.af.alle.de.ord..du.m.dte.i.unders.gelsen. = 'All_Words_Known') 
                                      )

# Reformat some of the columns
data_DK$Duration <- as.numeric(data_DK$Duration)
data_DK <- subset(data_DK, Finished =="True")

# Visualize data
head(data_DK)
rm(filename)
```


### Overall number of data points 
```{r Descriptives, message=FALSE}

paste('Total number of participants', as.character(nrow(data_DK)), sep = ': ')
paste('Total number of native speakers', as.character(nrow(subset(data_DK, Native == 'ja'))), sep = ': ')
paste('Number participants who knew the meaning of all words', as.character(nrow(subset(data_DK, Which_Unknown == ''))), sep = ': ')
paste('Number female', as.character(nrow(subset(data_DK, Gender == 'Kvinde'))), sep = ': ')

# Age distribution
agg_age <- data_DK %>% group_by(Age) %>% dplyr::summarize(Number_participants= n())
print('Age distribution')
paste('    18-30', as.character(agg_age$Number_participants[1]), sep = ': ')
paste('    30-40', as.character(agg_age$Number_participants[2]), sep = ': ')
paste('    40-50', as.character(agg_age$Number_participants[3]), sep = ': ')
paste('    50-60', as.character(agg_age$Number_participants[4]), sep = ': ')
paste('    60+  ', as.character(agg_age$Number_participants[5]), sep = ': ')


# Print duration
paste('Average duration (in minutes)', as.character(mean(data_DK$Duration) / 60))

# Clean up
rm(agg_age)

```

### Delete useless columns
```{r DropColsAndReshape, message = FALSE}

# Drop columns
#58, 59, 63
data_DK<-data_DK[ , -c(1:8, 10:17)]

# Reshape
data_DK <- melt(data_DK, id=c('ID','Gender','Age','Native', 'Mother_Tongue','All_Words_Known','Which_Unknown'))

# Remove datapoints wDKh unknown words
ID_unknown <- unique(subset(data_DK, Which_Unknown != '')$ID)

row_drops_1 <- which(data_DK$ID %in% ID_unknown[c(1, 3:7, 9:16)] & data_DK$variable == 'giftgople')
row_drops_2 <- which(data_DK$ID == ID_unknown[2] & data_DK$variable %in% c('forsvinden', 'gift'))
row_drops_3 <- which(data_DK$ID == ID_unknown[15] & data_DK$variable %in% c('kontrabas'))
row_drops_4 <- which(data_DK$ID == ID_unknown[12] & data_DK$variable %in% c('kontrabas', 'skovfl\345t'))
row_drops_5 <- which(data_DK$ID == ID_unknown[10] & data_DK$variable %in% c('patron'))

row_drops <- c(row_drops_1, row_drops_2, row_drops_3, row_drops_4, row_drops_5)
data_DK <- data_DK[-row_drops,]

# Rename columns
data_DK <- reshape::rename(data_DK, c(variable = 'Noun', value ='Demonstrative'))

# Remove useless variables
rm(ID_unknown, row_drops_1, row_drops_2, row_drops_3, row_drops_4, row_drops_5, row_drops)

```


### Info on experimental words
```{r ExpWords, message=FALSE}

# Add experimental words
Fillers_DK<-c('fred', 'forfremmelse', 'overraskelse', 'forandring', 'nederlag', 'skuffelse', 'skam', 'forsvinden')
 
Animals_DK<-c('tiger', 'kobra', 'krokodille', 'vildsvin', 'myg', 'giftgople', 'fugleedderkop', 'skovfl.t', 'giraf', 'hest', 'delfin', 'r.dyr', 'kanin' ,'sommerfugl','egern','spurv')
 
Bigger_DK<-c('meteor', 'lavine', 'vulkan', 'bombefly', 'tiger', 'kobra', 'krokodille', 'vildsvin', 'giraf', 'hest', 'delfin', 'r.dyr' ,'skole','egetr.','kontrabas','kuppel')

Harmful_DK<-c('tiger', 'kobra', 'krokodille','vildsvin','meteor', 'lavine', 'vulkan', 'bombefly', 'myg', 'giftgople', 'fugleedderkop', 'skovfl.t', 'landmine', 'gift', 'patron', 'kniv')

### Create column "Fillers" and resp. assign values "Fillers" and "Exp_words" based on values in $Noun
data_DK$Fillers <- ifelse(data_DK$Noun %in% Fillers_DK, "Fillers", "Exp_words")
data_DK$Fillers<-factor(data_DK$Fillers)

### Create column "Animal" and resp. assign values "Animate" and "Non_Animate" based on values in $Noun
data_DK$Animate <- ifelse(data_DK$Noun %in% Animals_DK, "Animate", "Non_Animate")
data_DK$Animate<-factor(data_DK$Animate)

### Create column "Size" and resp. assign values "Big" or "Small" based on values in $Noun
data_DK$Size <- ifelse(data_DK$Noun %in% Bigger_DK, "Big", "Small")
data_DK$Size<-factor(data_DK$Size)

### Create column "Harm" and resp. assign values "Harmful" or "Harmless" based on values in $Noun
data_DK$Harm <- ifelse(data_DK$Noun %in% Harmful_DK, "Harmful", "Harmless")
data_DK$Harm<-factor(data_DK$Harm)

# Values of Dems column as values in factor "Demonstratives"
data_DK$Demonstrative <- ifelse(data_DK$Demonstrative == 'den her' | data_DK$Demonstrative == 'det her', 'proximal', 'distal')
data_DK$Demonstrative<-factor(data_DK$Demonstrative)

# Remove fillers and delete column
data_DK_WithFillers <- data_DK
data_DK_WithFillers <- data_DK_WithFillers[, !(colnames(data_DK_WithFillers) %in%  c('Which_Unknown'))]

# Filter out fillers
data_DK <- subset(data_DK, Fillers != 'Fillers')
data_DK <- data_DK[, !(colnames(data_DK) %in%  c('Fillers', 'Which_Unknown'))]

# Re-visualize 
head(data_DK)
#write_tsv(data_DK, 'DK_2.txt')

# Remove useless variables
rm(Fillers_DK, Animals_DK, Bigger_DK, Harmful_DK)
```